[[redirects]]
  from = "/api/*"
  to = "https://api.hufstreaming.site/:splat"
  status = 200
  force = true
  headers = {Content-Type = "application/json"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200