[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/"
[headers.values]
Access-Control-Allow-Origin = ""

[[redirects]]
from = "/api/*"
to = "https://api.hufstreaming.site/:splat"
status = 200
force = true