[[redirects]]
from = "/api/*"
to = "https://api.hufstreaming.site/:splat"
status = 200
force = true
headers = { Access-Control-Allow-Origin = "*" }

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"